### ISSUE TITLE
How pas data in ${} like text widget in math.tex error adding data from another model class

### ISSUE THREAD

**Issue by alihassan143** [simpleclub-extended/flutter_math_fork#23]

**Comment by creativecreatorormaybenot** [comment]
Hi! Thanks for using the package. Unfortunately, I do not think this issue is actionable. If you have a coding question, you might want to ask that on [StackOverflow](https://stackoverflow.com/).

**Comment by alihassan143** [comment]
i am passing the custom equation but the parser showing error
