### ISSUE TITLE
Parser Error: Expected group after '^'

### ISSUE THREAD

**Issue by kevinxxq** [simpleclub-extended/flutter_math_fork#40]
Hi Team, Thank you for the package.
There is an error when I enter '^':
![image](https://user-images.githubusercontent.com/55800697/166857199-3da9742c-e973-4054-8b33-6528a51a7b2b.png)
The code:
```
Math.tex(
                  fitModelController.expr.value,
                  textStyle: TextStyle(color: Colors.green),
                  onErrorFallback: (err) => Container(
                    color: Colors.red,
                    child: Text(err.messageWithType,
                        style: TextStyle(color: Colors.yellow)),
                  ),
                ),
```

BTW, I would like to know whether it is only for web and mobile. The above codes are running on Win Desktop. No errors with the online demo.

Thank you.

**Comment by creativecreatorormaybenot** [comment]
Hey, this does look correct. What do you expect when entering ^?

See the demo at katex.org for example.

**Comment by kevinxxq** [comment]
Thank you @creativecreatorormaybenot
