### ISSUE TITLE
Request to Upgrade flutter_svg Dependency in flutter_math_fork

### ISSUE THREAD

**Issue by fei1025** [simpleclub-extended/flutter_math_fork#72]
Dear flutter_math_fork Maintainers,

I am currently using your package, flutter_math_fork, in my Flutter project and I appreciate the functionality it provides.  However, I have encountered a version conflict issue with the flutter_svg dependency.

My project requires the use of flutter_svg version 2.0.5, but flutter_math_fork currently depends on an older version of flutter_svg.  This version mismatch is causing conflicts and preventing my project from building successfully.

I kindly request that you consider upgrading the flutter_svg dependency in flutter_math_fork to version 2.0.5 or later.  This upgrade would resolve the version conflict and greatly assist in the progress of my project.

I understand that such an upgrade may have implications for other users of flutter_math_fork, and I appreciate the careful consideration that goes into maintaining package dependencies.

Thank you for your time and for the work you do maintaining flutter_math_fork.  I look forward to any updates you can provide on this matter.

**Comment by Sese-Schneider** [comment]
@fei1025 thank you for your request.
we're considering upgrading the dependency in the linked PR.

in the meantime, you could force overwrite the dependency with a [dependency overwrite](https://dart.dev/tools/pub/dependencies#dependency-overrides).
Please let us know if you encounter any issues there.
