### ISSUE TITLE
输入这种latex显示有误

### ISSUE THREAD

**Issue by szdenny2** [simpleclub-extended/flutter_math_fork#77]
输入这个latex公式解析有误，'3 \\times 5 + \\{ 1 + 2 \\} \\} '

原文如下
3*5+{1+2}}

当左边只有一个{ 括号，但是右边有2个 }}，就会出现问题。

**Comment by robin0822** [comment]
这不是数据有问题么？

**Comment by szdenny2** [comment]
![image](https://github.com/simpleclub-extended/flutter_math_fork/assets/18253729/30674ee5-d6a2-47c0-817d-427256afbb4e)
这个网址可以正常展示

**Comment by PassionPenguin** [comment]
Consider update your issue information, change your title to make it more readable to everyone.

---

latex like `1 + \{ 2 + 3 \}\}` can be parsed on latex 2023.

**Comment by Sese-Schneider** [comment]
Please reopen this issue with an English readable title and description
