### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by tjkhank** [simpleclub-extended/flutter_math_fork#83]
I have the following error when running on iOS

Running Xcode build...
Xcode build done.                                           27.6s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/flutter_math_fork-0.6.3+1/lib/src/widgets/selection/gesture_detector_builder.dart:186:20: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.

It runs without any issues on my Android phone.

I am rather new. Please advise.

thongjoon

**Comment by talkbiz** [comment]
Can you update to the latest version first?

**Comment by tjkhank** [comment]
Thank you so much for your reply.

I am using Android Studio Giraffe 2022.3.1 and Flutter 3.10.6

I am also using flutter_html 3.0.0-beta.2 and flutter_html_math 3.0.0-beta.2

On my Windows11machine, the math function displays perfectly well. I use an
iMac (2017 - Intel) for iOS device. The problem is on the iMac only.

Looking forward to hearing from you.

Thank you very much.
  Regards,
Thongjoon Khankhow

**Comment by tjkhank** [comment]
This is the message from iMac;

Running Xcode build...
Xcode build done.                                           13.0s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/
pub.dev/flutter_math_fork-0.6.3+1/lib/src/widgets/selection/gesture_detector_builder.dart:186:20:
Error: The argument type 'void Function(TapDownDetails)' can't be assigned
to the parameter type 'void Function(TapDragDownDetails)?'.


Error launching application on iPhone ของ สมศักดิ์.

**Comment by Sese-Schneider** [comment]
Fixed #87

**Comment by tjkhank** [comment]
Thank you so much for your attention to this matter.

I am happy to inform you that with the new flutter_math_fork: ^0.7.2, my
ios problem about fractions has been fixed.

If I may ask a question is that how can I make the size of the numerator
and the denominator a bit bigger.

Again, thank you so much for your work.

Regards,

Thongjoon Khankhow.
