### ISSUE TITLE
Hell, please fix the errorflutter_math_fork-0.7.1/lib/src/widgets/selection/gesture_detector_builder_selectable.dart:38:22: Error: 'TapDragUpDetails' isn't a type.   void onSingleTapUp(TapDragUpDetails details) {                      ^^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by OpenJarvisAI** [simpleclub-extended/flutter_math_fork#88]
flutter_math_fork-0.7.1/lib/src/widgets/selection/gesture_detector_builder_selectable.dart:38:22: Error: 'TapDragUpDetails' isn't a type.
  void onSingleTapUp(TapDragUpDetails details) {
                     ^^^^^^^^^^^^^^^^

**Comment by alex-hagiu** [comment]
https://github.com/alex-hagiu/flutter_math_fork

**Comment by bastulli** [comment]
Just add "import 'package:flutter/gestures.dart';" in gesture_detector_builder_selectable.dart as alex-hagiu mentioned

**Comment by Sese-Schneider** [comment]
Fixed #87

**Comment by Sese-Schneider** [comment]
cc: @alex-hagiu
